artifacts_root: ./artifacts


data_ingestion:
  root_dir : ./artifacts/data_ingestion
  source_url: https://github.com/KerithPaul/Project_Datasets/raw/refs/heads/main/winequality-red.zip
  local_data_file: ./artifacts/data_ingestion/winequality-red.zip
  unzip_dir: ./artifacts/data_ingestion